### ISSUE TITLE
Problem installing NativeLibs in Alpine

### ISSUE THREAD

**Issue by JJ** [salortiz/NativeLibs#7]
```
[NativeLibs] # Failed test 'No version found'
[NativeLibs] # at t/10-search.t line 22
[NativeLibs] # Failed test 'Can't be loaded'
[NativeLibs] # at t/10-search.t line 24
```
This is an (indirect) dependence of DBIish (through UUID), since it's not listed differently.

**Comment by JJ** [comment]
Had a look at this and the thing is that apparently, in Alpine, any number can be written after .so, it exists anyway. So only solution seems to be to install without tests.

**Comment by jubilatious1** [comment]
> Had a look at this and the thing is that apparently, in Alpine, any number can be written after .so, it exists anyway. So only solution seems to be to install without tests.

FYI, some discussion here:  https://www.nntp.perl.org/group/perl.perl6.users/2020/07/msg8930.html

@doomvox
@JJ

**Comment by salortiz** [comment]
The "linux" tests in `10-search.t` assume the presence of a recent version of libm.so (the one included with the standard glibc).
But Alpine linux don't use glibc, (in fact, by default, Alpine doesn't have a libm.so, To get one you should install the `libc6-compat` package)
The test should be modified with an special case for Alpine. PR welcomed.

DBDIsh **includes** its own (striped down) `NativeLibs` version without this tests, so _this_ should not be an issue for DBDIsh.

**Comment by jubilatious1** [comment]
Hi @salortiz, I'm just trying to understand the module installation process. I had an upgrade of Raku LibCurl fail on an older MacOS system and @CurtTilmes fixed it immediately. The issue and newest commit are listed below. Cheers. 

https://github.com/CurtTilmes/raku-libcurl/issues/16
https://github.com/CurtTilmes/raku-libcurl/commit/6c40cb4f818f10e7921aa724cf626853385bca9a

**Comment by salortiz** [comment]
@jubilatious1,
Yep, @CurtTilmes 's `LibRaku` was using a linux-only approach (search and preload the *.so file) that don't work on MacOS.
Nothing related with this issue.

**Comment by JJ** [comment]
Thanks for the comments. I'll check it out.

**Comment by JJ** [comment]
Done :arrow_double_up:

**Comment by jubilatious1** [comment]
> Yep, @CurtTilmes 's `LibRaku` was using a linux-only approach (search and preload the *.so file) that don't work on MacOS. Nothing related with this issue.

Thank you, @salortiz  !!   Regarding OS-specific issues, I did note that @doomvox was seeing an error loading Raku LibCurl. AFAIK, they're using an older version of Debian Linux. Maybe @doomvox will open an issue (or post a note on this one).

I guess the bigger question that is raised in my mind is whether Raku Modules that require native libraries can somehow 'register' with your NativeLibs Module, to offload the searching/preloading of OS-native modules. This way OS-specific problems (Linux, Mac, and hopefully Windows) could be handled with one tight code check.

Of course I'm thinking of @CurtTilmes 's Raku LibCurl module, but also @Skarsnik 's perl6-gumbo module, which depends on a previously-installed (Google) gumbo-parser:

https://github.com/Skarsnik/perl6-gumbo
https://github.com/google/gumbo-parser

Anyway, one can always dream! Best Regards.

CC: @JJ

**Comment by Skarsnik** [comment]
NativeCall already do proper lookup according to the OS if the libs are in standard path.

**Comment by jubilatious1** [comment]
@Skarsnik thank you for your reply.

1. So how common is the problem seen with native-LibCurl libraries, where a *.so file is appended with a numeric version? E.g. `libcurl.so.3` and or `libcurl.so.4` ?

2. Second of all, doesn't your perl6-gumbo module manage a separate location for Google's gumbo-parser called `PERL6_GUMBOLIB` ? 

3. Is `PERL6_GUMBOLIB` managed within your perl6-gumbo module, or is that a location that @salortiz 's NativeLibs knows about (and keeps track of)?

Sorry for all the questions, just trying to understand the Ecosystem. Thx.

**Comment by Skarsnik** [comment]
Because a .so is for devel purpose. If you read all the Unix spec a major version is mandatory and a lib should be named libfoo.so.major. You will find more about NC resolution at https://docs.raku.org/language/nativecall#ABI/API_version
